### PR TITLE
Bigquerycall fix

### PR DESCRIPTION
**Pull request by fernandalavalle**
Rearranged some dependencies and wrote unit tests for the BigQueryCall class.

[Review on Reviewable](https://reviewable.io/reviews/m-lab/telescope/84)

### CODE REVIEW

**Comment by mtlynch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 13 unresolved discussions.

---

*[telescope/external.py, line 34 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5I6d4KryKyxM2PLsAG:-K5I6d4KryKyxM2PLsAH:-2050521199) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/external.py#L34)):*
(not your fault, but since we're touching most of the references to this) This import violates the style guide:

>Use imports for packages and modules only.

https://google.github.io/styleguide/pyguide.html?showone=Imports#Imports

So we should just `import httplib` then replace references with `httplib.ResponseNotReady`

---

*[telescope/external.py, line 299 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IJ6domw0kMXgMAIMI:-K5IJ6domw0kMXgMAIMJ:1338462581) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/external.py#L299)):*
Dominant convention in Telescope is single quoted strings (ditto for other occurrences)

---

*[telescope/external.py, line 301 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5I4Opg2ywLErTELjTn:-K5I44a9eaJMIGtnUFWH:-1021827468) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/external.py#L301)):*
It's a little weird to have something that's so close to being a constructor for `BigQueryCall` but it's not the constructor.

I think the value of this function is that we don't want `BigQueryCall` to worry about dealing with `autheticate_with_google`. I suggest then changing this function to 
`def get_authenticated_service(google_auth_config)` and then change  `BigQueryCall`'s constructor to `def __init__(self, authenticated_service, project_id)`.

---

*[telescope/external.py, line 311 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5I6IQsZrSl9GqYs1qE:-K5I6IQsZrSl9GqYs1qF:-1775221151) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/external.py#L311)):*
(out of scope, but while you're here) Can we make this private? `self._project_id`?

---

*[telescope/external.py, line 313 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5I5s-Hc0t2EVUZJp4D:-K5I5s-Hc0t2EVUZJp4E:-1537147015) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/external.py#L313)):*
We don't need to try to catch this and re-wrap. It's the caller's responsibility to pass in a valid parameter that has this field.

---

*[telescope/external.py, line 334 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IHi3NdjwNgcDLCEBG:-K5IHi3OHU5g0dlSdLXG:148631511) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/external.py#L334)):*
(sorry, contradicting my earlier thoughts) I think a different error makes more sense here, because we're not really failing to communicate with BigQuery. We're successfully communicating with BigQuery (or at least speaking to something that speaks HTTP), but BigQuery reported failure. Suggest adding a new error like:

```
class BigQueryError(Exception):
  pass

class BigQueryFailedToStartQueryError(BigQueryError):
  ...
```

`BigQueryError` is just a base class Exception for this module (required by style guide: https://google.github.io/styleguide/pyguide.html?showone=Exceptions#Exceptions). We should have all exceptions in this file inherit from `BigQueryError`.

Then this function would do something like `raise BigQueryFailedToStartQueryError('Failed to start query job on BigQuery')`

---

*[telescope/telescope.py, line 396 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IJea7Jz5Ny7tymDR-:-K5IJea7Jz5Ny7tymDR0:1492831046) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/telescope.py#L396)):*
If we re-do the inheritance hierarchy for errors in external.py, then this can simplify to `except external.BigQueryError:`. I don't think it's possible for an un-wrapped `SSLError` to bubble back anymore.

---

*[telescope/telescope.py, line 397 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IJHVTNmBEjISBChKz:-K5IJHVTNmBEjISBChL-:-164597812) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/telescope.py#L397)):*
Intentionally left in? TODOs are fine, but we should put them in the form of `TODO(fernandalavalle): ...`

---

*[tests/test_external.py, line 26 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IJwP6JoiiBkxIiUDz:-K5IJwP6JoiiBkxIiUE-:-549756412) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/tests/test_external.py#L26)):*
Ditto for importing just `httplib`

---

*[tests/test_external.py, line 78 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IK-VZ0x0rhd32VIC_:-K5IK-VZ0x0rhd32VICa:-1940258774) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/tests/test_external.py#L78)):*
Extraneous blank line
Edit: Seems to repeat a few times in this file. Functions can never begin with a blank line, but beyond that try reducing the blank lines. We can use blanks to group sequences of instructions, but it seems like we could cut down a bit. It's a personal taste thing so I won't complain if you want blanks in places I'd consider them unnecessary.

---

*[tests/test_external.py, line 84 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IMy1IugTgtBqJxmW-:-K5IMy1IugTgtBqJxmW0:-1182734080) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/tests/test_external.py#L84)):*
I've been converted to verbose unit test function names, so I'll try to convert you. We're used to writing terse function names because you don't want all of your function's callers to type giant names. But test function names only need to be written once (never invoked in source) so that restriction is relaxed and we can be very verbose in test names.

I consider @stephen-soltesz's mlab-collectd unit tests to be a good example of this:

https://github.com/m-lab/collectd-mlab/blob/master/plugin/mlab_test.py

Also consider that when the test fails, the console output includes the test name and the first line of the docstring, so if it's hard to explain the purpose of the test fully in the function name, you can use the first line of the docstring to explain a little better.

So we might do something like:

```
def test_run_asynchronous_query_httpError(self):
    """BigQueryCall should wrap HttpError to a BigQueryError."""
    ...
```

---

*[tests/test_external.py, line 99 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IKLkTxwWkTznzvvdf:-K5IKLkTxwWkTznzvvdg:632570087) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/tests/test_external.py#L99)):*
Given that we only use `jobIdExpected` in one place, no need to assign it to a variable, can just be:

`self.assertEqual('dummy_job_id', job_id_actual)`

Also, we should update `jobIdActual` to use snake case

---

*[tests/test_external.py, line 125 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5ILDJ7Mi6AoL_M6FnJ:-K5ILDJ7Mi6AoL_M6FnK:-515852612) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/tests/test_external.py#L125)):*
Line > 80 chars. I'm surprised YAPF didn't whine about this, maybe because it doesn't know how to fix it. I think we can rewrite this as:

```
        self.mock_google_auth_config.authenticate_with_google.side_effect = (
            MockHttpError(404))
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/telescope/84)*

**Comment by mtlynch** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/telescope/84)*

**Comment by fernandalavalle** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[telescope/external.py, line 299 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IJ6domw0kMXgMAIMI:-K5WcPyY6weV6d3NPErI:-1253468624) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/external.py#L299)):*
is there an interesting reason why? or just a choice for consistency?

is this a default assumption for mlab things?

---

*[telescope/external.py, line 334 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IHi3NdjwNgcDLCEBG:-K5XFOR5BiQN_1QuI83o:221833370) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/external.py#L334)):*
so the unit for a single base class is a file? like all tests in external.py should inherit from BigQueryError?

---

*[tests/test_external.py, line 125 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5ILDJ7Mi6AoL_M6FnJ:-K5XDqeHIxS1t9IYBgq7:-1745315970) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/tests/test_external.py#L125)):*
I meant to ask, since this isn't technically a class method, is it bad form to include this test (or now in the second round a test testing get_authenticated_service) in BigQueryCallTest? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/telescope/84)*

**Comment by mtlynch** [comment]
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[telescope/external.py, line 299 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IJ6domw0kMXgMAIMI:-K5XXitpaY_yQXuIxxlR:-688590128) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/external.py#L299)):*
Yeah, just consistency. If we can get consistency for quotes across our projects, that'd be good (and I think dominant actually is single quoted), but for now I'm happy to just keep Telescope consistent with itself.

---

*[telescope/external.py, line 334 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5IHi3NdjwNgcDLCEBG:-K5XY6yTMY-y_RmDgnue:-975309741) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/telescope/external.py#L334)):*
Correct, all *error classes* in external.py should inherit from `BigQueryError` (which I think is what you menat). I think technically we're supposed to name it to match the module name, but `ExternalError` I think would be a super confusing name.

---

*[tests/test_external.py, line 125 \[r1\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5ILDJ7Mi6AoL_M6FnJ:-K5XYXiWDyXhuY-Z6SP_:245082081) ([raw file](https://github.com/m-lab/telescope/blob/874350c6d009c46bbbf38c15f1aedaa45b6af4bf/tests/test_external.py#L125)):*
Oh yeah, I'd put it in its own test class. I missed that.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/telescope/84)*

**Comment by mtlynch** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[telescope/external.py, line 23 \[r2\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5XqYWlCTf6TtBb-Tj2:-K5XqYWlCTf6TtBb-Tj3:1883908169) ([raw file](https://github.com/m-lab/telescope/blob/9d3b2ae5b3179e915274fd145d3dd5397050ae24/telescope/external.py#L23)):*
Can we put these in alphabetical order?

---

*[telescope/external.py, line 346 \[r2\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5aO_TTUPHUjJoXdzIU:-K5aO_TTUPHUjJoXdzIV:89592976) ([raw file](https://github.com/m-lab/telescope/blob/9d3b2ae5b3179e915274fd145d3dd5397050ae24/telescope/external.py#L346)):*
Now that `project_id` is given in the constructor, we can remove this `if` check entirely. We can assume the caller gave us a valid `project_id`.

---

*[telescope/telescope.py, line 400 \[r2\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5aPU292M06lzM2-XZ4:-K5aPU292M06lzM2-XZ5:-264658927) ([raw file](https://github.com/m-lab/telescope/blob/9d3b2ae5b3179e915274fd145d3dd5397050ae24/telescope/telescope.py#L400)):*
Suggest just `except external.BigQueryError as caught_error:`.

An `SSLError` shouldn't be able to bubble back after your changes.

We can alternatively enumerate `BigQueryJobFailure` and `BigQueryCommunicationError` (i.e. just delete the `SSLError` part). It's more complex, but it does prevent us from catching an exception that doesn't make sense (e.g. if we catch all `BigQueryError`s we'd also catch `TableNotFoundError` here even though we don't really want to).

---

*[tests/test_external.py, line 26 \[r2\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5aPsZMw3A04tFbGrcV:-K5aPsZMw3A04tFbGrcW:-982108057) ([raw file](https://github.com/m-lab/telescope/blob/9d3b2ae5b3179e915274fd145d3dd5397050ae24/tests/test_external.py#L26)):*
Should be in the first group of `import`s (standard library `import`s) in alphabetical order.

https://google.github.io/styleguide/pyguide.html?showone=Imports_formatting#Imports_formatting

---

*[tests/test_external.py, line 78 \[r2\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5aQQy4ElF3XsSToV1d:-K5aQQy4ElF3XsSToV1e:-1498079931) ([raw file](https://github.com/m-lab/telescope/blob/9d3b2ae5b3179e915274fd145d3dd5397050ae24/tests/test_external.py#L78)):*
Some double quotes got left behind in this file

---

*[tests/test_external.py, line 103 \[r2\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5aQk01CRh0s0E0Xmej:-K5aQk01CRh0s0E0Xmek:440773736) ([raw file](https://github.com/m-lab/telescope/blob/9d3b2ae5b3179e915274fd145d3dd5397050ae24/tests/test_external.py#L103)):*
(nitpick) Suggest preserving case of "proper nouns" so I'd say `test_run_asynchronous_query_HttpError` (ditto for `ResponseNotReady`)

---

*[tests/test_external.py, line 111 \[r2\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5aQxAdnt9rnJcIPqkW:-K5aQxAdnt9rnJcIPqkX:301889753) ([raw file](https://github.com/m-lab/telescope/blob/9d3b2ae5b3179e915274fd145d3dd5397050ae24/tests/test_external.py#L111)):*
`HttpError` -> `ResponseNotReady`

---

*[tests/test_external.py, line 128 \[r2\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5aR4emeLXznE2BTe1B:-K5aR4emeLXznE2BTe1C:1279877848) ([raw file](https://github.com/m-lab/telescope/blob/9d3b2ae5b3179e915274fd145d3dd5397050ae24/tests/test_external.py#L128)):*
Can we also add a success case?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/telescope/84)*

**Comment by mtlynch** [comment]
LGTM

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tests/test_external.py, line 82 \[r3\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5bnIcFcBAYa_NXW9YY:-K5bnIcFcBAYa_NXW9YZ:1422462685) ([raw file](https://github.com/m-lab/telescope/blob/1772ca2e10f892db9a25c490295996dcdcac6993/tests/test_external.py#L82)):*
Whoops missed this earlier. First line in a docstring should always end in period. (ditto for rest of file)

---

*[tests/test_external.py, line 136 \[r3\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5booBVDfpDfEKXmGSh:-K5booBVDfpDfEKXmGSi:-743100045) ([raw file](https://github.com/m-lab/telescope/blob/1772ca2e10f892db9a25c490295996dcdcac6993/tests/test_external.py#L136)):*
Suggest `"""Should succeed when the call to authenticate_with_google succeeds."""`

---

*[tests/test_external.py, line 138 \[r3\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5bnqBnFCqTb6M3tPtW:-K5bnqBnFCqTb6M3tPtX:1011367123) ([raw file](https://github.com/m-lab/telescope/blob/1772ca2e10f892db9a25c490295996dcdcac6993/tests/test_external.py#L138)):*
 Over 80 chars, can fix with:

```
        self.mock_google_auth_config.authenticate_with_google.return_value = (
            mock_authenticated_service)
```

---

*[tests/test_external.py, line 143 \[r3\]](https://reviewable.io:443/reviews/m-lab/telescope/84#-K5bnTDzDXZOZ3GHaUvP:-K5bnTDzDXZOZ3GHaUvQ:-732169426) ([raw file](https://github.com/m-lab/telescope/blob/1772ca2e10f892db9a25c490295996dcdcac6993/tests/test_external.py#L143)):*
One of these should probably be `mock_authenticated_service` otherwise it's not a very exciting test.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/telescope/84#-:-K5bphNqISh1OeVcg2DT:676834233)*

**Pull request merged**
