### PR TITLE
Fixing divide by zero error in average_rtt query

### PR DESCRIPTION
**Pull request by mtlynch**
There are rows in BigQuery that strangely have `CountRTT` as 0 even though `HCThruOctetsAcked` > 0 (which seems invalid to me, but I'm maybe missing something). The SQL generation assumed that an explicit check on `CountRTT` > 0 was unnecessary because we were already checking that `HCThruOctetsAcked` >= 8192, but it looks like we need to check both fields.

[Review on Reviewable](https://reviewable.io/reviews/m-lab/telescope/75)

Update: Talked to Matt Mathis, `CountRTT` as 0 and `HCThruOctetsAcked` > 0 is a valid NDT result:
> CountRTT is the count of RTT measurements and is only intended to be used with SumRTT to compute a true mean RTT.   Since RTT measurements can be spoiled, for example if the segment being timed is retransmitted, there may be fewer CountRTTs than actual RTTs.   Completing a (short) connection with zero measurements is not very unusual.

### CODE REVIEW

**Comment by mtlynch** [comment]
You can ignore the build break. This is a bug in our travis config, I've filed #76.

**Comment by collina** [comment]
I'm not a fan of this hypothesis as to why the event occurs, but I am okay with the inclusion of the conditional. Please also document it in the Wiki, outside of that this looks good to me and I will take the remainder to the email thread.


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/telescope/75)

**Comment by mtlynch** [comment]
Interestingly it was documented all along in the PDE wiki:

>Server-client latency during data transfers (with congestion)
Estimated using the average RTT, uniformly averaged over an entire test.
This value can be computed as web100_log_entry.snap.SumRTT/web100_log_entry.snap.CountRTT
In this case, it makes sense to exclude results of tests with fewer than 10 round trip time samples, because there are not enough samples to accurately estimate the RTT. This condition is expressed in BigQuery with:web100_log_entry.snap.CountRTT > 10

https://github.com/m-lab/mlab-wikis/blob/master/PDEChartsNDT.md#round-trip-time-rtt

But then the example shows `web100_log_entry.snap.CountRTT > 0`

I think we should use the > 10 rule (as this is what PDE is doing internally) and adjust the wording to "exclude results of tests with *10 or fewer*".

I'll send a separate PR fixing PDE wiki.

Can you review the latest revision as these are material changes to the code?


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/telescope/75)

**Comment by collina** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/telescope/75)

**Pull request merged**
